# costmap_common_params_thi_exploration
# configuration options for local costmap and global costmap

# Setting thresholds on obstacle information into the costmap:

# obstacle_range: determiniaton of the maximum range sensor reading that will result an obstacle putting into the costmap

# raytrace_range: determiniation of the range to which we will raytrace freespace given a sensor reading.

obstacle_range: 2.5
raytrace_range: 3.0

# Set the footprint of the robot
robot_radius: 0.05

# the robot will treat all paths that stay x meters or more away from obstacles as having equal obstacle cost.
inflation_radius: 0.15

# observation_sources: Definition of a list sensors that are going to be passing information to the costmap 
observation_sources: laser_scan_sensor

# laser_scan_sensor:
# frame_name: set to the name of the coordinate frame of the sensor
# data_type: set to LaserScan, dependency of used topic 
# topic_name: set to the name of the topic that the sensor publishes data on
# marking: determination add obstacle information to the costmap
# clearing: clear obstacle information from the costmap

# Laser scan sensor for the simulation
laser_scan_sensor: {sensor_frame: robot0_laser_0, data_type: LaserScan, topic: robot0/laser_0, marking: true, clearing: true} 

# Laser scan sensor for the SICK nanoScan3
# laser_scan_sensor: {sensor_frame: scan, data_type: LaserScan, topic: sick_safetyscanners/scan
# , marking: true, clearing: true} 
