robot:
  robot_specifications:
    - footprint:
        footprint_specifications:
          radius: 0.05
    - initial_pose:
        x: 0
        y: 0
        theta: 0
    - laser:
        laser_specifications:
          max_angle: 1.5
          min_angle: -1.5
          max_range: 10.0
          min_range: 0.06
          num_rays: 667
          frequency: 10
          frame_id: laser_0
          pose:
            x: 0
            y: 0
            theta: 0
          # noise:
          #   noise_specifications:
          #     noise_mean: 0.5
          #     noise_std: 0.0500000007450581
