# local_costmap_params_thi_exploration

# like in global_costmap_params_thi_exploration

local_costmap:
  global_frame: robot0
  robot_base_frame: robot0
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false

# publish_frequency: determination of the rate, at which the costmap will publish visualization information. 
# rolling_window: Setting to true means that the costmap will remain centered around the robot as the robot moves through the world
# width, height and resolution: setting width, height (meters) and resolution (meters/cell) of the costmap. 

  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.05

